### ISSUE TITLE
B12.1 Draft Software Release Documentation and Updates

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-github-util#47]
In preparation for B12.1, we should plan to continue to evolve our release documentation

- [ ] ~split out RDD (internal use) from Software Summary (external users)~
- [x] throw warnings for requirements / bugs that have "unknown" priority / severity
- [x] random newlines throughout the RDD:
<img width="719" alt="Screen Shot 2021-11-02 at 8 51 57 AM" src="https://user-images.githubusercontent.com/33492486/139885164-454beca8-dd70-4291-9dc8-690963fbe3f0.png">
- [ ] Software summary has formatting bug:
<img width="363" alt="Screen Shot 2021-11-02 at 8 52 53 AM" src="https://user-images.githubusercontent.com/33492486/139885529-c8399f45-f8db-43f2-a885-c0c8d2278395.png">
 - [x] we should clarify what "(no epic in this repository)" means? does this mean no issues associated with this Epic in this repository?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams can you be more specific about this bullet "split out RDD (internal use) from Software Summary (external users)" ? Thanks

**Comment by jordanpadams** [comment]
@tloubrieu-jpl I crossed it out for now. Ideally we can figure out what kind of system build documentation we can produce for the average user. maybe it is just the release summaries with link to newer/better release notes.

**Comment by jordanpadams** [comment]
moving to next sprint as we prep for the build

**Comment by jordanpadams** [comment]
@tloubrieu-jpl a couple other updates needed:
<img width="1020" alt="Screen Shot 2022-03-29 at 2 22 55 PM" src="https://user-images.githubusercontent.com/33492486/160709491-92ec39cf-e8b8-4424-9b19-fefc3a1e36b2.png">

<img width="1016" alt="Screen Shot 2022-03-29 at 2 24 01 PM" src="https://user-images.githubusercontent.com/33492486/160709613-31535e17-e16b-4f5b-9650-f1eebe001c19.png">

**Comment by jordanpadams** [comment]
remaining open items not found. closing as completed.
